// <auto-generated>
//     Phase 20 / Improvement #18 — каркас локализации.
//
//     Это РУЧНОЙ designer-файл (не сгенерирован VS), потому что SDK-style
//     csproj в режиме <EmbeddedResource> с пользовательскими LogicalName
//     несовместим с автогенерацией через ResXFileCodeGenerator. Если будем
//     добавлять ключи, дописываем их сюда руками — это всё равно read-only
//     обёртка над ResourceManager.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace AhuErp.Core.Resources
{
    /// <summary>
    /// Доступ к локализованным строкам приложения. Куль­тура выбирается
    /// автоматически через <see cref="CultureInfo.CurrentUICulture"/>.
    /// Английская спутниковая сборка строится из <c>Strings.en.resx</c>.
    /// </summary>
    public static class Strings
    {
        private static readonly ResourceManager _rm =
            new ResourceManager("AhuErp.Core.Resources.Strings", typeof(Strings).Assembly);

        /// <summary>Низкоуровневый доступ к ResourceManager (для тестов).</summary>
        public static ResourceManager ResourceManager => _rm;

        /// <summary>Получить строку по ключу с подстановкой формата.</summary>
        public static string Get(string key, params object[] args)
        {
            var value = _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;
            return args == null || args.Length == 0
                ? value
                : string.Format(CultureInfo.CurrentUICulture, value, args);
        }

        public static string App_Refresh => Get(nameof(App_Refresh));
        public static string App_OK => Get(nameof(App_OK));
        public static string App_Cancel => Get(nameof(App_Cancel));
        public static string App_Save => Get(nameof(App_Save));

        public static string Procurement_Module => Get(nameof(Procurement_Module));
        public static string Procurement_PlansTitle => Get(nameof(Procurement_PlansTitle));
        public static string Procurement_ContractsTitle => Get(nameof(Procurement_ContractsTitle));
        public static string Procurement_UpcomingMilestonesTitle => Get(nameof(Procurement_UpcomingMilestonesTitle));
        public static string Procurement_TotalCommitted => Get(nameof(Procurement_TotalCommitted));
        public static string Procurement_Year => Get(nameof(Procurement_Year));
        public static string Procurement_Title => Get(nameof(Procurement_Title));
        public static string Procurement_Status => Get(nameof(Procurement_Status));
        public static string Procurement_EisRegistration => Get(nameof(Procurement_EisRegistration));
        public static string Procurement_SupplierName => Get(nameof(Procurement_SupplierName));
        public static string Procurement_ContractAmount => Get(nameof(Procurement_ContractAmount));
        public static string Procurement_RegistrationNumber => Get(nameof(Procurement_RegistrationNumber));

        public static string Validation_YearRequired => Get(nameof(Validation_YearRequired));
        public static string Validation_PlanTitleRequired => Get(nameof(Validation_PlanTitleRequired));
        public static string Validation_EisRegistrationRequired => Get(nameof(Validation_EisRegistrationRequired));
    }
}
